package constant

const (
	DEBUG_MODE_FLAG           = "DEBUG_MODE_FLAG"
	APP_PORT                  = "APP_PORT"
	TRUSTED_PROXIES           = "TRUSTED_PROXIES"
	PROMETHEUS_FLAG           = "PROMETHEUS_FLAG"
	REDISDB_HOST              = "REDISDB_HOST"
	REDISDB_PORT              = "REDISDB_PORT"
	REDISDB_PASSWORD          = "REDISDB_PASSWORD"
	MONGODB_USERNAME          = "MONGODB_USERNAME"
	MONGODB_PASSWORD          = "MONGODB_PASSWORD"
	MONGODB_DATABASE          = "MONGODB_DATABASE"
	MONGODB_CONNECTION_STRING = "MONGODB_CONNECTION_STRING"
	POSTGRESDB_HOST           = "POSTGRESDB_HOST"
	POSTGRESDB_PORT           = "POSTGRESDB_PORT"
	POSTGRESDB_USERNAME       = "POSTGRESDB_USERNAME"
	POSTGRESDB_PASSWORD       = "POSTGRESDB_PASSWORD"
	POSTGRESDB_MIGRATION_FLAG = "POSTGRESDB_MIGRATION_FLAG"
)
